
GET http://localhost:3000/blogs?page=2&limit=10

###

GET http://localhost:3000/users?page=1&limit=5

###

GET http://localhost:3000/surnames?page=1640&limit=10

###

GET http://localhost:3000/people?page=1900&limit=10

###

GET http://localhost:3000/restaurants?page=2&limit=900

###

GET http://localhost:3000/contacts?page=1&limit=50