
GET http://localhost:8800

###

GET http://localhost:8800/blogs?page=1&limit=10

###

GET http://localhost:8800/users?page=1&limit=5

###

GET http://localhost:8800/surnames?page=1&limit=10

###

GET http://localhost:8800/people?page=1&limit=10

###

GET http://localhost:8800/restaurants?page=2&limit=900

###

GET http://localhost:8800/contacts?page=1&limit=50